---
title: "PhysicalComments"
author: "Mikhail Kurenkov"
date: "03 11 2021"
output: html_document
---

```{r load_packages}

library(tidyverse)
library(showtext)
library(patchwork)

font_add_google("Oswald", "oswald")
font_add_google("Roboto Condensed", "roboto condensed")
font_add_google("Share Tech Mono", "techmono")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)

## Автор начинает с загрузки нескольких пакетов - помимо стандартного tidyverse он также использует showtext и patchwork. Первый позволяет использовать больше разнообразных шрифтов и графических решений для визауализации данных, а второй - упрощает совмещение нескольких ggplot в одном графике. Плюс загружены новые шрифты.

```

Link to download the data :

https://www.kaggle.com/heesoo37/120-years-of-olympic-history-athletes-and-results

```{r load_data}

athletes <- read_csv(here::here("input", "athlete_events.csv"))

```

```{r data_prep}

athletes <- athletes %>%
    mutate(Sex = ifelse(Sex == "F", "Women", "Men"))

## Автор трансформирует существующий набор данных "athletes" с помощью инструмента mutate, создавая две дополнительные колонки "women" и "men" + с помощью ifelse создаёт вектор, где yes соотнесено с переменной women, а no - с men  

# Years for the labels & breaks
years <- athletes %>% filter(Season == "Summer") %>% distinct(Year) 

## Автор с помощью инструмента filter группирует данные, распределяя их по годам и выделяя только летний период 

# Dataset for outliers

## Автор создаёт отдельные переменные для выбросов --> атлетов с выделяющимися показателями возраста 

oldest <- athletes %>%
  filter(!is.na(Medal), Season =="Summer") %>%
  group_by(Sex) %>%
  slice_max(Age, n= 1) %>% 
  ungroup()

## Автор создаёт переменную для самых пожилых атлетов. С помощью функции is.na опредеделяется истинность наличия медали за летний сезон Олимпийских игр. Затем автор группирует выделенное множество по полу и с помощью функции slice_max выбирает строки с наибольшим значением переменных.Также используется инструмент ungroup для того, чтобы в дальнейшем вести расчёты на всём множестве атлетов. 

youngest <- athletes %>%
  filter(!is.na(Medal), Season =="Summer") %>%
  group_by(Sex) %>%
  slice_min(Age, n= 1) %>%
  ungroup()

## Автор также создаёт переменную для самых молодых атлетов. Всё так же как и в примере выше, за исключением того, что используется функция slice_min, которая, в противоположность предыдущей, выбирает строки с наименьшим значением (т.е. возраста). 

extreme <- youngest %>%
  bind_rows(oldest) %>%
  select(Name, Age, Sex, Year, Sport, Medal, Team, ID)

## Автор соаздаёт отдельную общую переменную для самых молодых и самых пожилых атлетов. Для этого он использует инструмент bind_rows, который позволяет совместить два фрейма данных (в нашем случае oldest и youngest). Затем с помощью select автор выделяет это подмножество из всего множества в соотвествии с указанными переменными (name - ID)

arrows <- tibble(x = c(1906, 1938, 1936, 1960),
                 y = c(8, 8, 69, 73))

## Автор задаёт связь между парами значений для отображения их на графике. Непонятно почему два наименьших значения - 8 и 8, когда на самом графике этим атлетам по 10 и 11 лет соотвественно. 

arrows <- arrows %>% 
  bind_cols(extreme) %>%
  mutate(text = glue::glue("{Name} - {Age} yo - {Team} - {Medal} {Sport}"))

## С помощью bind_cols автор связывает фреймы данных по столбцам и затем с помощью glue объединяет строки - в том виде, в котором затем они будут представлены на графике.

# Remove outliers from the main dataset (because of jitter it would display the point aside)
athletes <- athletes %>%
  filter(!ID %in% extreme$ID)

## Здесь автор выделяет из общего фрейма данных с атлетами подмножество extreme, с которым работал до этого. 

ylabels <- tibble(x = rep(1892, 7),
                  y = seq(10, 70, 10))

## Автор выставляет пограничные значения для осей координат по оси x и y, где первая соотвествует годам, а вторая - возрасту спортсменов. 
```

```{r colors}

palette <- c("Men" = "#03A696", "Women" = "#F25D27")
update_geom_defaults("text", list(family = "roboto condensed"))

## Автор присваивает цвета для каждой переменной men и women и с помощью update_geom_defaults устанавливает эту эстетику для всех графиков по умолчанию

```


```{r main_plot}

age_distribution <- athletes %>%
  filter(!is.na(Medal), Season =="Summer") %>%
  ggplot() +
  geom_text(data = ylabels, aes(x, y, label = y), color = "grey70", nudge_y = 1) +
  geom_segment(data = years, aes(x = Year, xend = Year, y = 0 , yend = 20), linetype = "14", color = "grey70", inherit.aes = FALSE, size = 0.3)+
  geom_jitter(aes(Year, Age, fill = Sex), width = 1.5, size = 1.7, shape = 21, stroke = 0.1, color = "black")+
  geom_point(data = arrows, aes(x = Year, y = Age, fill = Sex), size = 3.5, shape = 21, stroke = 0.3, color = "black") +
  geom_curve(data = filter(arrows, Age > 60), aes(x = x, y = y, xend = Year, yend = Age), arrow = arrow(length = unit(0.1,"cm")), curvature = 0.4, color = "white") +
  geom_curve(data = filter(arrows, Age < 15), aes(x = x, y = y, xend = Year, yend = Age), arrow = arrow(length = unit(0.1,"cm")), curvature = -0.4, color = "white") +  
  geom_text(data = arrows[1:2,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 0, vjust = 0.4) +
  geom_text(data = arrows[4,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 0) +
  geom_text(data = arrows[3,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 1, vjust = 0.6) +
  scale_fill_manual(values = palette) +
  scale_x_continuous(breaks = years$Year, limits = c(1892, 2018), expand = c(0.02,0.02)) +
  scale_y_continuous(breaks = seq(10, 70, 10)) +
  guides(fill = FALSE) +
  theme_void() +
  theme(panel.background = element_rect(fill = "grey20", color = NA),
        panel.grid.major.y = element_line(linetype = "14", size = 0.3, color = "grey70"),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, margin = margin(-40, 10, 10, 0), color = "grey70", vjust = -0.3, size = 12, family = "roboto condensed"))

## Здесь автор строит основной график, состоящий, преимущественно, из geom_text и geom_point, предварительно, как и раньше, использовав filter для определения наличия у атлета медали и выделения таковых из всего множества атлетов, участвовавших в играх. Использует jitter для увеличения общего числа визуализированных данных. С помощью geom_segment делает пунктирные линии для удобства разделения количества атлетов, а с помощью geom_curve - непрямые линии для визуализации рекордсменов-"выбросов" - старше 60 и младше 15 лет соотвественно.С помощью scale - закрашивает график цветами, используя выделенную ранее переменную palette (в которой разные цвета присвоены men и women) + определяет пределы этого закрашивания. С помощью theme - присваивает фону стандартную тему void, а также определяет шрифт надписей на нём с помощью axis.text

```


```{r sex_distribution}

sex_distribution <- athletes %>%
  filter(!is.na(Medal), Season =="Summer") %>%
  arrange(Year) %>%
  group_by(Sex, Year) %>%
  summarise(total = n()) %>%
  ungroup() %>%
  ggplot(aes(Year, total, fill = Sex)) +
  geom_col() +
  scale_fill_manual(values = palette) +
  scale_x_continuous(limits = c(1892, 2018), expand = c(0.02,0.02)) +
  guides(fill = guide_legend(label.position = "top",
                               title.hjust = 0.5,
                               keywidth = unit(3, "line"),
                               keyheight = unit(1, "line"),
                               nrow = 1
                               )) +
  theme_void() +
  theme(panel.background = element_rect(fill = "grey20", color = NA),
        legend.position = c(0.1, 0.90),
        legend.title = element_blank(),
        legend.text = element_text(family = "oswald", face = "bold", size = 12, color = "#D8E6F2"))

## Здесь автор создаёт дополнительный график для визуализации разделения множества по значению sex, предварительно как обычно использовав filter для выделения медалистов из общего множества атлетов. С arrange разделяет их по годам. Он использует вид графика geom_col, а также закрашивает его цветом по созданной ранее переменной palette - также и ограничивая пределы закрашивания + c помощью guides устанавливает напрявление для каждой шкалы. 
```

```{r assemble}

final <- sex_distribution / age_distribution +
  plot_layout(nrow = 2, heights = c(0.5,2)) +
    plot_annotation(
      title = "Age & sex distribution of the medalists in the Summer Olympic Games",
      subtitle = "And a focus on the oldest and the youngest athletes for women and men.",
      caption = "#30DayChartChallenge Day 7 | Viz: Christophe Nicault | Data: www.sports-reference.com / Kaggle",
      theme = theme(
        plot.background = element_rect(fill = "grey20", color = NA),
        plot.title = element_text(family = "oswald", size = 18, color = "white", hjust = 0.5, face = "bold", margin = margin(10,0,0,0)),
        plot.subtitle = element_text(family = "oswald", color = "white", size = 14, hjust = 0.5, margin = margin(10,0,15,0)),
        plot.caption = element_text(family = "techmono", color = "grey80", size = 10, hjust = 0.98)      
      )
    )

## Здесь автор объединяет в одном пространстве, написанные ранее графики с распределением атлетов по sex (график с geom_col) и age (график с geom_text и geom_point) с помощью инструмента plot_layout + задаёт цвета и шрифты для описания визуализированных данных. 

ragg::agg_png(here::here("render", paste0("30DayChartChallenge_day7", format(Sys.time(), "%Y%m%d_%H%M%S"), ".png")), res = 320, width = 14, height = 10, units = "in")

 ## И в конце концов рендерит это всё в картинку
final
  
dev.off()

```



